server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway: 
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*, *" 
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*" 
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-SERVICE
                fallbackuri: forward:/customerServiceFallback

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallback

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallback

        - id: DCS-WEBSOCKET-SERVICE
          uri: lb://DCS-WEBSOCKET-SERVICE
          predicates:
            - Path=/websocket/**
          filters:
            - name: CircuitBreaker
              args:
                name: DCS-WEBSOCKET-SERVICE
                fallbackuri: forward:/websocketServiceFallback
                
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

