server:
  port: 9005

spring:
  jpa:
    hibernate:
      ddl-auto : update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/h2/order-service
    username: sa
    password:
    driverClassName: org.h2.Driver
  application:
    name: ORDER-SERVICE
  zipkin:
    url: http://127.0.0.1:9411
  main:
    allow-circular-references: true
