apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          env:
            - name: DB_HOST
              value: mysql 

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8888       # Port exposed inside the cluster
      targetPort: 8888 # Container port
      nodePort:   30001
  type: NodePort       # Optional: expose to your host system (Docker Desktop)
