server:
  port: 9001
spring:
  application:
    name: PRODUCT-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/h2/product-service;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
  zipkin:
    url: http://127.0.0.1:9411
  main:
    allow-circular-references: true
# openai:
#   model: gpt-3.5-turbo
#   api:
#     url: https://api.openai.com/v1/chat/completions
#     key: *****
minio:
  buckek:
    name: anji
  default:
    folder: / 
  access:
    name: minioadmin
    secret: minioadmin
  url: http://127.0.0.1:9000