server:
  port: 9001
spring:
  application:
    name: PRODUCT-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/product-service
      username: sa
      password:
      driverClassName: org.h2.Driver
  zipkin:
    url: http://127.0.0.1:9411
  main:
    allow-circular-references: true